name: drivex_app
description: DriveX - Elite Car Rental App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  supabase_flutter: ^2.5.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
